---
apiVersion: v1
kind: Service
metadata:
  name: app-api
spec:
  type: LoadBalancer
  selector:
    app: app-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    app: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
      - name: app-api
        image: europe-west9-docker.pkg.dev/GOOGLE_PROJECT/demo/app-api:latest
